version: 0.2

env:
  parameter-store:
    # Optional: store Docker Hub credentials in AWS Parameter Store
    DOCKERHUB_USERNAME: /myapp/dockerhub/username
    DOCKERHUB_PASSWORD: /myapp/dockerhub/password
    DOCKERHUB_REPO: /myapp/dockerhub/repo
  # If not using Parameter Store, configure these as CodeBuild environment variables

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm ci
      - echo "Docker should be available in CodeBuild for this project."
  pre_build:
    commands:
      - echo "Logging in to Docker Hub..."
      # Use Docker Hub credentials from environment or Secrets Manager
      - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - IMAGE_TAG="${DOCKERHUB_TAG:-latest}"
      - IMAGE_NAME="${DOCKERHUB_REPO:-kvedansh786/crud-app}:${IMAGE_TAG}"
      - echo "Will build image: $IMAGE_NAME"
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t "${IMAGE_NAME}" .
  post_build:
    commands:
      - echo "Pushing Docker image to Docker Hub..."
      - docker push "${IMAGE_NAME}"
      - echo "Docker image pushed: ${IMAGE_NAME}"
      - docker images | head -n 20

artifacts:
  files:
    - '**/*'