services:
  backend:
    container_name: nodejs_crud_app
    build:
      context: .
      dockerfile: dockerfile
    ports:
    - "8082:8082"
    environment:
    - MONGO_URL=mongodb://mongodb:27017/studetail
    depends_on:
    - mongodb
    networks:
    - crud-app
    restart: unless-stopped

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
    - "27017:27017"
    volumes:
    - mongo-data:/data/db
    networks:
    - crud-app
    healthcheck:
      test: ["CMD","mongosh","--eval","db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: unless-stopped

volumes:
  mongo-data:
    driver: Local

networks:
  crud-app:
    driver: bridge